// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	EditMessage(ctx context.Context, arg EditMessageParams) (Message, error)
	GetMessagesByRoom(ctx context.Context, arg GetMessagesByRoomParams) ([]GetMessagesByRoomRow, error)
}

var _ Querier = (*Queries)(nil)
