// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	DeleteRoom(ctx context.Context, id pgtype.UUID) error
	GetRoomById(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]GetRoomMembersRow, error)
	IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error)
	ListRooms(ctx context.Context) ([]Room, error)
	ListRoomsByUser(ctx context.Context, userID pgtype.UUID) ([]Room, error)
	RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
