// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, user_id, content, type)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, user_id, content, type, edited_at, created_at
`

type CreateMessageParams struct {
	RoomID  pgtype.UUID `json:"room_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Content string      `json:"content"`
	Type    string      `json:"type"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.RoomID,
		arg.UserID,
		arg.Content,
		arg.Type,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Content,
		&i.Type,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1 AND room_id = $2
`

type DeleteMessageParams struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.RoomID)
	return err
}

const getMessagesByRoom = `-- name: GetMessagesByRoom :many
SELECT m.id, m.room_id, m.user_id, m.content, m.type, m.edited_at, m.created_at, u.username, u.display_name FROM messages m
JOIN users u ON m.user_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMessagesByRoomParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetMessagesByRoomRow struct {
	ID          pgtype.UUID        `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Content     string             `json:"content"`
	Type        string             `json:"type"`
	EditedAt    pgtype.Timestamptz `json:"edited_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
}

func (q *Queries) GetMessagesByRoom(ctx context.Context, arg GetMessagesByRoomParams) ([]GetMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesByRoomRow{}
	for rows.Next() {
		var i GetMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Content,
			&i.Type,
			&i.EditedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
