// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   string             `json:"content"`
	Type      string             `json:"type"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	IsPublic        bool               `json:"is_public"`
	MaxParticipants int32              `json:"max_participants"`
	Settings        []byte             `json:"settings"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	RoomID   pgtype.UUID        `json:"room_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Password    string             `json:"password"`
	DisplayName pgtype.Text        `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
