// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteRoom(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	GetMessagesByRoom(ctx context.Context, arg GetMessagesByRoomParams) ([]GetMessagesByRoomRow, error)
	GetRoomById(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]GetRoomMembersRow, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error)
	ListRooms(ctx context.Context) ([]Room, error)
	ListRoomsByUser(ctx context.Context, userID pgtype.UUID) ([]Room, error)
	RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
