// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddRoomMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember, arg.RoomID, arg.UserID, arg.Role)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, owner_id, is_public, max_participants)
VALUES ($1, $2, $3, $4)
RETURNING id, name, owner_id, is_public, max_participants, settings, created_at
`

type CreateRoomParams struct {
	Name            string      `json:"name"`
	OwnerID         pgtype.UUID `json:"owner_id"`
	IsPublic        bool        `json:"is_public"`
	MaxParticipants int32       `json:"max_participants"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Name,
		arg.OwnerID,
		arg.IsPublic,
		arg.MaxParticipants,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IsPublic,
		&i.MaxParticipants,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getRoomById = `-- name: GetRoomById :one
SELECT id, name, owner_id, is_public, max_participants, settings, created_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoomById(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomById, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IsPublic,
		&i.MaxParticipants,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT u.id, u.username, u.email, u.password, u.display_name, u.created_at, u.updated_at, rm.role, rm.joined_at FROM users u
JOIN room_members rm ON u.id = rm.user_id
WHERE rm.room_id = $1
ORDER BY rm.joined_at ASC
`

type GetRoomMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Password    string             `json:"password"`
	DisplayName pgtype.Text        `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]GetRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomMembersRow{}
	for rows.Next() {
		var i GetRoomMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isRoomMember = `-- name: IsRoomMember :one
SELECT EXISTS(SELECT 1 FROM room_members WHERE room_id = $1 AND user_id = $2)
`

type IsRoomMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRoomMember, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, owner_id, is_public, max_participants, settings, created_at FROM rooms ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.IsPublic,
			&i.MaxParticipants,
			&i.Settings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsByUser = `-- name: ListRoomsByUser :many
SELECT r.id, r.name, r.owner_id, r.is_public, r.max_participants, r.settings, r.created_at FROM rooms r
JOIN room_members rm ON r.id = rm.room_id
WHERE rm.user_id = $1
ORDER BY r.created_at DESC
`

func (q *Queries) ListRoomsByUser(ctx context.Context, userID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.IsPublic,
			&i.MaxParticipants,
			&i.Settings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomMember = `-- name: RemoveRoomMember :exec
DELETE FROM room_members WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomMemberParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) error {
	_, err := q.db.Exec(ctx, removeRoomMember, arg.RoomID, arg.UserID)
	return err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = COALESCE($2, name),
    is_public = COALESCE($3, is_public),
    max_participants = COALESCE($4, max_participants),
    settings = COALESCE($5, settings)
WHERE id = $1
RETURNING id, name, owner_id, is_public, max_participants, settings, created_at
`

type UpdateRoomParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	IsPublic        bool        `json:"is_public"`
	MaxParticipants int32       `json:"max_participants"`
	Settings        []byte      `json:"settings"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.IsPublic,
		arg.MaxParticipants,
		arg.Settings,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IsPublic,
		&i.MaxParticipants,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}
